"use client";

import {useEffect,useState} from "react";
import type {RemediationAttempt} from "@localmesh/shared";

type Session={authenticated:boolean;csrf?:string;user?:{login:string}};
type Original={path:string;sql:string;direction:string};
export function RemediationLab({jobId}:{jobId:string}) {
  const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4100";const [session,setSession]=useState<Session>();const [attempt,setAttempt]=useState<RemediationAttempt>();const [originals,setOriginals]=useState<Original[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("Checking GitHub access…");
  useEffect(()=>{void fetch(`${api}/api/session`,{credentials:"include"}).then((response)=>response.json()).then((value:Session)=>{setSession(value);setMessage(value.authenticated?"Ready to generate candidates with the configured local model.":"Sign in to verify repository access before remediation.");}).catch(()=>setMessage("The authentication service is unavailable."));},[api]);
  async function run(){if(!session?.csrf)return;setBusy(true);setMessage("Generating candidates, then replaying every deterministic check. This can take several minutes.");try{const response=await fetch(`${api}/api/jobs/${encodeURIComponent(jobId)}/remediate`,{method:"POST",credentials:"include",headers:{"content-type":"application/json","x-dot75-csrf":session.csrf},body:"{}"});const queued=await response.json() as {attemptId?:string;error?:string};if(!response.ok||!queued.attemptId)throw new Error(queued.error??"Remediation failed");let completed:{status:string;result?:RemediationAttempt;originalFiles?:Original[];error?:string}|undefined;for(let index=0;index<300;index++){await new Promise((resolve)=>setTimeout(resolve,2000));const statusResponse=await fetch(`${api}/api/remediations/${encodeURIComponent(queued.attemptId)}`,{credentials:"include"});const status=await statusResponse.json() as typeof completed;if(!statusResponse.ok)throw new Error(status?.error??"Remediation status could not be loaded");if(status?.status==="completed"||status?.status==="failed"){completed=status;break;}}if(!completed)throw new Error("Remediation is still running. Refresh this page to inspect it later.");if(completed.status==="failed"||!completed.result)throw new Error(completed.error??"Remediation worker failed");setAttempt(completed.result);setOriginals(completed.originalFiles??[]);setMessage("Verification complete. Candidates remain local and have not changed the repository.");}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setBusy(false);}}
  function patchText(candidate:RemediationAttempt["candidates"][number]){return candidate.patches.map((patch)=>`--- a/${patch.path}\n+++ b/${patch.path}\n@@ complete migration replacement @@\n${patch.sql}`).join("\n\n");}
  function download(candidate:RemediationAttempt["candidates"][number]){const text=patchText(candidate);const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([text],{type:"text/x-diff"}));link.download=`dot75-${candidate.id}.patch`;link.click();URL.revokeObjectURL(link.href);}
  if(session&&!session.authenticated)return <section className="contract-auth"><div className="product-kicker">GitHub authorization required</div><h2>Keep remediation repository-scoped</h2><p>{message}</p><a className="primary-button" href={`${api}/auth/github?returnTo=${encodeURIComponent(`/jobs/${jobId}/remediation`)}`}>Sign in with GitHub</a></section>;
  return <div className="remediation-workspace"><div className="remediation-control" aria-live="polite"><p>{message}</p><button className="primary-button" type="button" disabled={busy||!session?.authenticated} onClick={run}>{busy?"Verifying candidates…":"Generate and verify candidates"}</button></div>
    {attempt&&<section><div className="remediation-meta"><span>Model {attempt.model??"unavailable"}</span><span>Prompt v{attempt.promptVersion}</span><span>{Math.round(attempt.durationMs/1000)} seconds</span><span>Receipt {attempt.sourceDigest.slice(0,12)}</span></div>{attempt.error&&<p className="fallback-notice">{attempt.error}</p>}
      <div className="remediation-candidates">{attempt.candidates.map((candidate)=><article key={candidate.id} className={`remediation-candidate ${candidate.status}`}><header><span>{candidate.status}</span><h2>{candidate.title}</h2><p>{candidate.rationale}</p></header>{candidate.patches.map((patch)=><div key={patch.path}><h3>{patch.path}</h3><div className="sql-comparison"><div><b>Original</b><pre>{originals.find((item)=>item.path===patch.path)?.sql??"Original SQL unavailable"}</pre></div><div><b>Candidate</b><pre>{patch.sql}</pre></div></div></div>)}
        <div className="candidate-actions"><button type="button" onClick={()=>navigator.clipboard.writeText(patchText(candidate))}>Copy patch</button><button type="button" onClick={()=>download(candidate)}>Download patch</button></div><p className="candidate-evidence">{candidate.status==="verified"?`Verified: ${candidate.verification?.orders.length??0} execution order(s), contracts, fixture state, configured groups, and rollback policies passed.`:candidate.rejectionReason??"The candidate was not verified."}</p>{candidate.assumptions.length>0&&<details><summary>Assumptions ({candidate.assumptions.length})</summary><ul>{candidate.assumptions.map((assumption,index)=><li key={index}>{assumption}</li>)}</ul></details>}
      </article>)}</div>{attempt.candidates.length===0&&<p className="empty-inline">No repair candidate was produced. The deterministic verdict is unchanged.</p>}</section>}
  </div>;
}
